### ISSUE TITLE
[BUG]: resnet18 run failed on x86

### ISSUE THREAD

**Issue by pengl** [alibaba/heterogeneity-aware-lowering-and-optimization#111]
**Describe the bug**
car detect resnet18 run failed on x86

**To Reproduce**
link resnet18.cc with dnnl.so, and execute resnet18.exe.

**Expected behavior**
exit without error

**Screenshots**
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/1219619/102864413-0b811680-446f-11eb-99c3-4d35491715ff.png">

**Additional context**
"terminate called after throwing an instance of 'dnnl::error'
  what():  could not create a descriptor for a deconvolution forward propagation primitive
Aborted (core dumped)"

**Comment by weimingzha0** [comment]
Can you add the options passed to HALO?

**Comment by xuhongyao** [comment]
The latest code did not reproduce the problem, but a new bug appeared PR#113

**Comment by xuhongyao** [comment]
@pengl PR#115 may fix it
