### ISSUE TITLE
[BUG] inception-v3 model incorrect shape

### ISSUE THREAD

**Issue by xuhongyao** [alibaba/heterogeneity-aware-lowering-and-optimization#126]
**Describe the bug**

incorrectly parse the shape in the inception-v3 model, as the red font part 

halo IR
![image](https://user-images.githubusercontent.com/74580362/104144847-e34a5f00-53ff-11eb-9d2c-d49a64112b0b.png)

![image](https://user-images.githubusercontent.com/74580362/104144773-a2524a80-53ff-11eb-806a-a249d8f0365d.png)

**To Reproduce**

pr #124 
remove "XFAIL: *" in models/vision/classification/inception/run_inception_v3.sh, then run "ninja check-halo-models"

**Expected behavior**

**Screenshots**

**Additional context**
Fix ONNX weight parsing #104

**Comment by weimingzha0** [comment]
Looks like "Gather" produces an extra dimension mistakenly. The final rank should be Q + R - 1, where Q is the rank of input tensor and R is the rank of index tensor.

**Comment by weimingzha0** [comment]
resolved
