### ISSUE TITLE
dnnl maxpooling support attribute "ceil mode"

### ISSUE THREAD

**Issue by xuhongyao** [alibaba/heterogeneity-aware-lowering-and-optimization#150]
**Describe the bug**
https://github.com/alibaba/heterogeneity-aware-lowering-and-optimization/pull/146/checks?check_run_id=1736476571
terminate called after throwing an instance of 'dnnl::error'
  what():  could not create a descriptor for a pooling forward propagation primitive
/host/heterogeneity-aware-lowering-and-optimization/halo/models/vision/classification/squeezenet/run_squeezenet_1_0.sh: line 25:  5032 Aborted                 (core dumped) python3 $curr_dir/../../invoke_halo.py --model $model_file --label-file $curr_dir/../1000_labels.txt --image-dir $image_dir --odla dnnl --convert-layout-to=nhwc

**To Reproduce**
execute vision/classification/squeezenet/run_squeezenet_1_0.sh
or ninja check-halo-models

**Expected behavior**

**Screenshots**

**Additional context**
the ceil_mode is not considered in dnnl pooling_desc_init
ceil_mode: whether to use ceil or floor (default) to compute the output shape
https://github.com/oneapi-src/oneDNN/blob/master/src/common/pooling.cpp line 111

**Comment by weimingzha0** [comment]
related issue on DNNL: https://github.com/oneapi-src/oneDNN/issues/513

**Comment by weimingzha0** [comment]
one workaround is to use a C function instead of JIT engine (like topK)
