### ISSUE TITLE
[BUG] [DNNL] expand_dims

### ISSUE THREAD

**Issue by weimingzha0** [alibaba/heterogeneity-aware-lowering-and-optimization#155]
**Describe the bug**
expand_dims() seems incorrect

**To Reproduce**

if src has shape [C], dst has shape [N, C, H, W], the current function will make src as [1, 1, 1, C], which is incorrect.
It should follow the broadcasting rule.

**Comment by ahuizxc** [comment]
> **Describe the bug**
> expand_dims() seems incorrect
> 
> **To Reproduce**
> 
> if src has shape [C], dst has shape [N, C, H, W], the current function will make src as [1, 1, 1, C], which is incorrect.
> It should follow the broadcasting rule.

in tensorflow, it will throw an error if lhs and rhs shape is [C] and [N,C,H,W], is the test model from onnx?
