### ISSUE TITLE
[BUG]Failed to compile halo according to docs/how_to_build.md

### ISSUE THREAD

**Issue by leaf-yyl** [alibaba/heterogeneity-aware-lowering-and-optimization#443]
**To Reproduce**
Clone the halo code and build docker with utils/docker/Dockerfile
execute start_docker_gpu.sh and docker exec -it root.halo-latest-GPU /bin/bash
cd Halo && mkdir build && cd build
Add  include_directories(${CUDA_ROOT}/include/thrust/system/cuda/detail) to ODLA/platforms/tensorrt/CMakeLists.txt  on line 22 below set(CUDA_ROOT /usr/local/cuda-${CUDA_VERSION}/targets/x86_64-linux)

cmake -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Release -DODLA_BUILD_POPART=OFF -DODLA_BUILD_DNNL=OFF -DODLA_BUILD_EIGEN=OFF -DODLA_BUILD_XNNPACK=OFF -DCMAKE_CUDA_STANDARD_REQUIRED=TRUE -DGPU_ARCHS=70 -G Ninja ../
ninja
Failed to compile halo with errors below:
/usr/local/cuda-10.0/targets/x86_64-linux/include/thrust/system/cuda/detail/cub/device/../iterator/arg_index_input_iterator.cuh(120): error: KeyValuePair is not a template
/usr/local/cuda-10.0/targets/x86_64-linux/include/thrust/system/cuda/detail/cub/device/dispatch/../../agent/agent_reduce.cuh(65): error: identifier "BlockReduceAlgorithm" is undefined
/usr/local/cuda-10.0/targets/x86_64-linux/include/thrust/system/cuda/detail/cub/device/dispatch/../../agent/agent_reduce.cuh(66): error: identifier "CacheLoadModifier" is undefined

**Additional context**
Executing cmake with config as below still leads to compilation failure(errors are same as above)
cmake  -DCMAKE_BUILD_TYPE=Release -DODLA_BUILD_POPART=OFF  -DGPU_ARCHS=70 -G Ninja ..

**Comment by wangchang-2020** [comment]
（1）“execute start_docker_gpu.sh and docker exec -it root.halo-latest-GPU /bin/bash”
这里不需要使用root 用户，普通用户就可以，执行start_docker_gpu.sh 脚本后应该可以直接进入容器，不需要再执行后面的 exec命令； 多次进入容器 也可以直接执行该脚本。

（2）“Add include_directories(${CUDA_ROOT}/include/thrust/system/cuda/detail).....”
我之前也有过类似操作，之所以添加这个是因为 cub头文件找不到。 cub头文件找不到是 tensorrt 下的cub 子项目没有下载下来，我使用以下命令可以递归下载子项目，然后可以正确的找到cub项目中的头文件了。
git submodule sync --recursive
git -c protocol.version=2 submodule update --init --force --depth=1 --recursive
git submodule foreach --recursive git config --local gc.auto 0

（3）popart 开启支持，需要下载popart 的SDK，可以在oss 上找到：
http://search-ad.oss-cn-hangzhou-zmf.aliyuncs.com/wangchang/sdk2.1.ubuntu.tar.bz2
修改heterogeneity-aware-lowering-and-optimization/ODLA/platforms/odla_popart/CMakeLists.txt 文件中的POPLAR_ROOT 变量，将其指向下载的SDK包中的目录。

**Comment by leaf-yyl** [comment]
> （1）“execute start_docker_gpu.sh and docker exec -it root.halo-latest-GPU /bin/bash”
> 这里不需要使用root 用户，普通用户就可以，执行start_docker_gpu.sh 脚本后应该可以直接进入容器，不需要再执行后面的 exec命令； 多次进入容器 也可以直接执行该脚本。
> 
> （2）“Add include_directories(${CUDA_ROOT}/include/thrust/system/cuda/detail).....”
> 我之前也有过类似操作，之所以添加这个是因为 cub头文件找不到。 cub头文件找不到是 tensorrt 下的cub 子项目没有下载下来，我使用以下命令可以递归下载子项目，然后可以正确的找到cub项目中的头文件了。
> git submodule sync --recursive
> git -c protocol.version=2 submodule update --init --force --depth=1 --recursive
> git submodule foreach --recursive git config --local gc.auto 0

Thank you for you advice. Git clone the project manually with all sub modules, I have build the project successfully.
