### ISSUE TITLE
[BUG] wrong bias size parse for tflite model

### ISSUE THREAD

**Issue by huangteng** [alibaba/heterogeneity-aware-lowering-and-optimization#63]
**Describe the bug**
when parsing mobilenet_v2_1.0_224.tflite using halo, it parses bias size as tensor output size.
mobilenet model downloaded from https://storage.googleapis.com/download.tensorflow.org/models/tflite_11_05_08/mobilenet_v2_1.0_224.tgz

**To Reproduce**

heterogeneity-aware-lowering-and-optimization/build/bin/halo -exec-mode=interpret -emit-value-id-as-int -emit-data-as-c -target cxx ./mobilenet_v2_1.0_224.tflite -o ./mobilenet_v2_1.cc

**Expected behavior**
it generates: extern const float inst_112_bias_broadcasted_181[1 * 112 * 112 * 32];
however, the correct bias size should be 32 float.

**Screenshots**
![image](https://user-images.githubusercontent.com/4410358/101230605-3afaf980-36e1-11eb-80ba-6f942484b4a0.png)

**Comment by weimingzha0** [comment]
Can you try -disable-broadcasting ?
Thanks

**Comment by huangteng** [comment]
yes, -disable-broadcasting solves the problem.

**Comment by weimingzha0** [comment]
Thanks. I will close it
