### ISSUE TITLE
[BUG] ODLA/Popart should use ODLA_USE_SIM_MODE instead of ODLA_USE_SIM_MODEL

### ISSUE THREAD

**Issue by weimingzha0** [alibaba/heterogeneity-aware-lowering-and-optimization#68]
**Describe the bug**
Build error when ODLA/Popart is enabled

**To Reproduce**

See the build of of PR 61: https://github.com/alibaba/heterogeneity-aware-lowering-and-optimization/pull/61/checks?check_run_id=1514167986

**Comment by youbeny** [comment]
fixed,  https://github.com/alibaba/heterogeneity-aware-lowering-and-optimization/pull/69
