### ISSUE TITLE
[BUG] Sub-graph compilation can't work with the option of "outputs"  

### ISSUE THREAD

**Issue by zhangnju** [alibaba/heterogeneity-aware-lowering-and-optimization#83]
**Describe the bug**
sub-graph compilation should work with the option of "outputs", but when I assigned to the output node to be Conv/Conv2D for Tensorflow version LPRnet, the whole graph was still compiled.   

**To Reproduce**
./halo -target cxx /home/LPRNet_Models/tensorflow/lprnet_new_v2.pb -reorder-data-layout=channel-last -disable-broadcasting  -remove-input-transpose -remove-output-transpose -o lprnet_conv.cc -entry-func-name=lprnet_conv -outputs=Conv/Conv2D

**Expected behavior**
a sub-graph with the output node of "conv/conv2d" should be compiled 

**Screenshots**
output node was still d_predictions instead of conv/conv2d 
void lprnet_conv(const float input_1[1 * 24 * 94 * 3],
                 float out_d_predictions[1 * 88 * 71]) {
  lprnet_conv_init();
  static odla_context Ctx;
  if (Ctx == nullptr) {
    odla_CreateContext(&Ctx);
  };
  odla_BindToArgumentById((const odla_value_id) "input_1", input_1, Ctx);
  odla_BindToOutputById((const odla_value_id) "d_predictions",
                        out_d_predictions, Ctx);
  odla_ExecuteComputation(Comp, Ctx, ODLA_COMPUTE_INFERENCE, nullptr);
}

**Additional context**
I check the codes in driver.cc, the output node name has some requirements, but the node name with slash can often be found at TF model. so it is better for HALO to support the node name with slash. 
static llvm::cl::list<std::string> Outputs(
    "outputs",
    llvm::cl::desc("Specify output names like -outputs=foo, -outputs=bar:0"));

**Comment by weimingzha0** [comment]
how about 
```bash
-outputs='Conv/Conv2D'
```
?
