### ISSUE TITLE
[BUG]: g++ compile error using halo's output

### ISSUE THREAD

**Issue by pengl** [alibaba/heterogeneity-aware-lowering-and-optimization#93]
**Describe the bug** 
<model-name>.cc could not be read by g++ compiler correctly, and it'll report "<class_ 'type'>" could not be recognized.

**To Reproduce**
g++ -c -o <model-name>.o <model-name>.cc -I<INCLUDE_PATH>

**Expected behavior**
exit normally and output <model-name>.o

**Screenshots**
<img width="436" alt="image" src="https://user-images.githubusercontent.com/1219619/102033572-c1f15580-3df6-11eb-8915-ded2cb3707ee.png">

**Comment by weimingzha0** [comment]
https://github.com/alibaba/heterogeneity-aware-lowering-and-optimization/pull/90 should fix it
