### ISSUE TITLE
[BUG] Packed constants in TF not handled properly

### ISSUE THREAD

**Issue by weimingzha0** [alibaba/heterogeneity-aware-lowering-and-optimization#95]
**Describe the bug**
for values like [a, a,...], TF saved it as a single {a}.
TF parser doesn't handle it properly.

**To Reproduce**

Command lines to reproduce the bug.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by youbeny** [comment]
If shape is set, the value is reshaped to match. Scalars are expanded to fill the shape:
```
print(tf.Session().run(tf.constant(0, shape=(2,3))))
>>>[[0 0 0]
    [0 0 0]]

```
